RewriteEngine On

# Only allow WebSocket connections
RewriteCond %{HTTP:Upgrade} !^websocket$ [NC]
RewriteRule ^(.*)$ https://example.com/ [R=302,L]

# For WebSocket requests
<If "%{HTTP:Upgrade} =~ /websocket/i">
    ProxyPreserveHost On
    ProxyPass "/" "ws://127.0.0.1:9008/"
    ProxyPassReverse "/" "ws://127.0.0.1:9008/"
</If>