/home/{username}/logs/cli/*.log /home/{username}/logs/cron/*.log {
	su {username} {username}
	weekly
	rotate 3
	maxsize 80M
	compress
	delaycompress
	create 0640 {username} {username}
	notifempty
	missingok
	sharedscripts
}