root /home/{username}/app/public;

# Deprecated in most cases: ENVIRONMENT is handled via .env; only use when a custom env file (e.g. .env.dev) is required
#fastcgi_param CI_ENV production;
# Serve well-know files directly
location ^~ /.well-known/ {
	try_files $uri /;
}
# Serve static assets directly
location ~ ^/(media|assets)/ {
	try_files $uri =404;
	access_log off;
	expires 30d;
}
# Main application routing, passes the entire request URI (path + query string) as part of the query string
location / {
	try_files $uri $uri/ /index.php?/$request_uri;
}

# PHP-FPM configuration
location ~ "\.php(/|$)" {
	try_files $uri $fastcgi_script_name =404;
	default_type application/x-httpd-php;
	# Update the socket path to match your PHP 
	fastcgi_pass unix:/run/php/php-fpm.sock; 
}
